version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./user_service/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  user_service:
    build: ./user_service
    container_name: user_service
    restart: always
    depends_on:
      - db
    env_file:
      - ./user_service/.env
    ports:
      - "8000:8000"

  gateway:
    build: ./gateway
    container_name: gateway
    restart: always
    depends_on:
      - user_service
    env_file:
      - ./gateway/.env
    ports:
      - "3000:3000"

volumes:
  db_data:
